domain: docs.ubuntu.com

image: prod-comms.ps5.docker-registry.canonical.com/docs.ubuntu.com

env:
  - name: SENTRY_DSN
    value: https://02a19f51f9eb4db6ab3d1da5f07be823@sentry.is.canonical.com//38

useProxy: false

readinessPath: "/"

# Overrides for production
production:
  replicas: 5

  nginxConfigurationSnippet: |
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3

  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
